# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MB Coffee Farm
logo: /assets/images/mb-logo.png
favicon: /assets/images/favicon.ico
email: mbcoffeefarm@gmail.com
description: >-   
  Premium Guji coffee directly from our family farm in Ethiopia.
twitter_username: 
github_username: 
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Output settings
# Controls the permalink format for blog posts — you can ignore if you're not using blog posts
permalink: /:categories/:title/

# Pagination settings — disabled to avoid showing blog post feed on homepage
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/

# Timezone (optional but recommended)
timezone: # e.g., America/Los_Angeles

# Include custom directories like _pages
include:
  - _pages

# Plugins used for features like sitemap, emoji, etc.
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author information (shown on pages if enabled)
author:
  name   : "Aman Gedefaw"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Founder of MB Coffee – sharing Guji's best beans with the world."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://gedefaws.github.io/gedefaws-mbcoffee.github.io"
    # Uncomment if you'd like to display social profiles
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Footer links (displayed at the bottom of every page)
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mbcoffee@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gedefaws"

# Page defaults
defaults:
  # Applies to all pages (unless overridden)
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # Specifically for pages in the _pages folder (like home.md, about.md, etc.)
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      css: /assets/css/custom.css

# Blog archive pages — okay to keep, even if not used yet
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
